# Generated by Django 4.2.15 on 2024-08-24 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Novel_chapter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chapter_id", models.IntegerField(default=0, verbose_name="章节号")),
                (
                    "title",
                    models.CharField(default=None, max_length=64, verbose_name="章节标题"),
                ),
                (
                    "content",
                    models.FileField(
                        blank=True, upload_to="novel_content", verbose_name="章节内容"
                    ),
                ),
                ("words", models.IntegerField(default=0, verbose_name="字数")),
                ("novel_id", models.IntegerField(null=True, verbose_name="用户ID")),
            ],
            options={
                "verbose_name_plural": "小说章节表",
                "unique_together": {("novel_id", "chapter_id")},
            },
        ),
    ]
