# Generated by Django 2.2.28 on 2024-08-26 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cfi', models.CharField(max_length=255, verbose_name='CFI位置')),
                ('note', models.TextField(verbose_name='笔记内容')),
                ('user_id', models.IntegerField(verbose_name='用户ID')),
                ('novel_id', models.IntegerField(verbose_name='小说ID')),
                ('chapter_id', models.IntegerField(verbose_name='章节ID')),
                ('is_public', models.BooleanField(default=False, verbose_name='是否公开')),
                ('type', models.CharField(default=None, max_length=255, verbose_name='具体类型')),
            ],
            options={
                'verbose_name_plural': '书签表',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_time', models.DateTimeField(auto_now_add=True)),
                ('comment_content', models.TextField()),
                ('user_id', models.IntegerField(default=None, verbose_name='用户ID')),
                ('novel_id', models.IntegerField(default=None, verbose_name='小说ID')),
                ('chapter_id', models.IntegerField(default=0, verbose_name='章节ID')),
                ('up_number', models.IntegerField(default=0, verbose_name='评分')),
            ],
            options={
                'verbose_name_plural': '评论表',
            },
        ),
        migrations.CreateModel(
            name='NovelChapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_id', models.IntegerField(default=0, verbose_name='章节号')),
                ('title', models.CharField(default=None, max_length=64, verbose_name='章节标题')),
                ('content', models.FileField(blank=True, upload_to='novel_content', verbose_name='章节内容')),
                ('words', models.IntegerField(default=0, verbose_name='字数')),
                ('novel_id', models.IntegerField(null=True, verbose_name='用户ID')),
            ],
            options={
                'verbose_name_plural': '小说章节表',
                'unique_together': {('novel_id', 'chapter_id')},
            },
        ),
        migrations.CreateModel(
            name='RecentlyReading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('novel_id', models.IntegerField(null=True, verbose_name='小说ID')),
                ('user_id', models.IntegerField(default=None, verbose_name='用户ID')),
                ('chapter_id', models.IntegerField(null=True, verbose_name='章节ID')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name_plural': '最近阅读表',
            },
        ),
        migrations.DeleteModel(
            name='Novel_chapter',
        ),
    ]
