apiVersion: apps/v1
kind: Deployment
metadata:
  name: web # 修改 Deployment 名字为 web-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web # 修改匹配的 label 为 web-1
  template:
    metadata:
      labels:
        app: web # 修改 label 为 web-1
    spec:
      containers:
      - name: web # 修改容器的名字为 web-1
        image: backend-image # 修改镜像名字为 code-web
        ports:
        - containerPort: 8000
        env:
          - name: DATABASE_URL
            value: "mysql://root:root@db:3306/RP2024"

        # pizza_change: 添加健康检查探针
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 20
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service # 可以修改 Service 名字为 web-1-service
spec:
  selector:
    app: web # 确保选择器与 Deployment 中的 label 一致
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30000
  type: NodePort