apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: novel-vpa
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: novel-service
  updatePolicy:
    updateMode: Auto
  resourcePolicy:
    containerPolicies:
    - containerName: novel-service
      minAllowed:
        cpu: 200m
        memory: 200Mi
      maxAllowed:
        cpu: 400m
        memory: 400Mi