apiVersion: apps/v1
kind: Deployment
metadata:
  name: reader_service # 修改 Deployment 名字为 reader_service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reader_service # 修改匹配的 label 为 reader_service
  template:
    metadata:
      labels:
        app: reader_service # 修改 label 为 reader_service
    spec:
      containers:
      - name: reader_service # 修改容器的名字为 reader_service
        image: backend-image # 修改镜像名字为 code-reader_service
        ports:
        - containerPort: 8002
        env:
          - name: DATABASE_URL
            value: "mysql://root:root@db:3306/RP2024"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service # 可以修改 Service 名字为 reader_service-service
spec:
  selector:
    app: reader_service # 确保选择器与 Deployment 中的 label 一致
  ports:
    - protocol: TCP
      port: 8002
      targetPort: 8002
      nodePort: 30002
  type: NodePort