apiVersion: apps/v1
kind: Deployment
metadata:
  name: reader-service # 修改 Deployment 名字为 reader-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reader-service # 修改匹配的 label 为 reader-service
  template:
    metadata:
      labels:
        app: reader-service # 修改 label 为 reader-service
    spec:
      containers:
      - name: reader-service # 修改容器的名字为 reader-service
      # 这里设置成如果镜像存在就不拉取
        imagePullPolicy: IfNotPresent
        image: reader-service-image # 修改镜像名字为 reader-service-image
        ports:
        - containerPort: 8000
        env:
          - name: DATABASE-URL
            value: "mysql://root:root@reader-db:3306/reader"
---
apiVersion: v1
kind: Service
metadata:
  name: reader-service # 可以修改 Service 名字为 reader-service-service
spec:
  selector:
    app: reader-service # 确保选择器与 Deployment 中的 label 一致
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30002
  type: NodePort