# Generated by Django 3.2 on 2024-06-08 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_icon',
            field=models.FileField(default='user_icon/default.jpg', upload_to='user_icon', verbose_name='用户头像'),
        ),
    ]
