# Generated by Django 3.2 on 2024-06-08 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='出生日期'),
        ),
        migrations.AddField(
            model_name='user',
            name='signature',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='个性签名'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_icon',
            field=models.FileField(default='user_icon/default.jpg', upload_to='user_icon', verbose_name='用户头像'),
        ),
    ]
