# Generated by Django 3.2 on 2024-06-08 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_user_icon'),
        ('users', '0003_auto_20240609_0043'),
    ]

    operations = [
    ]
