# Generated by Django 3.2 on 2024-06-10 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_merge_20240609_0756'),
        ('users', '0004_merge_20240609_1601'),
    ]

    operations = [
    ]
