# Generated by Django 3.2 on 2024-05-23 16:32

import apps.novels.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=32, verbose_name='作者')),
                ('author_gender', models.IntegerField(choices=[(0, '男'), (1, '女')], default=0, verbose_name='作者性别')),
                ('author_detail', models.TextField(default='', verbose_name='作者简介')),
                ('author_icon', models.FileField(default='icon/default.jpg', upload_to='icon/', verbose_name='作者图片')),
            ],
            options={
                'verbose_name_plural': '作者表',
            },
        ),
        migrations.CreateModel(
            name='Novel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('novel_img', models.FileField(default='image/default.jpg', upload_to='image/', verbose_name='小说图片')),
                ('novel_status', models.IntegerField(choices=[(0, '连载中'), (1, '已完结')], verbose_name='小说状态')),
                ('novel_name', models.CharField(max_length=64, verbose_name='小说名字')),
                ('detail', models.TextField(verbose_name='小说简介')),
                ('tuijian', models.IntegerField(default=0, verbose_name='推荐数量')),
                ('shubi', models.IntegerField(default=0, verbose_name='书币')),
                ('jinpiao', models.IntegerField(default=0, verbose_name='金票')),
                ('dashang', models.IntegerField(default=0, verbose_name='打赏数量')),
                ('dianji', models.IntegerField(default=0, verbose_name='点击数量')),
                ('total_words', models.IntegerField(default=0, verbose_name='总字数')),
                ('chapter_start', models.IntegerField(default=0, verbose_name='小说章节开始id')),
                ('chapter_end', models.IntegerField(default=0, verbose_name='小说章节结束id')),
                ('is_vip', models.IntegerField(default=0)),
                ('author', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Novel', to='novels.author', verbose_name='小说作者')),
            ],
            options={
                'verbose_name_plural': '小说表',
            },
        ),
        migrations.CreateModel(
            name='Novel_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=64, verbose_name='分类名字')),
                ('category_file', models.FileField(default='category/default.jpg', upload_to='category/', verbose_name='分类图片')),
            ],
            options={
                'verbose_name_plural': '小说分类表',
            },
        ),
        migrations.CreateModel(
            name='Novel_chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_free', models.BooleanField(default=True, verbose_name='是否免费')),
                ('price', models.IntegerField(default=0, verbose_name='价格')),
                ('novel_chapter', models.CharField(max_length=64, verbose_name='小说章节')),
                ('content', models.CharField(max_length=255, verbose_name='章节路径')),
                ('words', models.IntegerField(default=0, verbose_name='字数')),
                ('novel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Novel', to='novels.novel', verbose_name='小说外键')),
            ],
            options={
                'verbose_name_plural': '小说章节表',
            },
        ),
        migrations.CreateModel(
            name='recently_reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('Novel', models.ForeignKey(db_constraint=apps.novels.models.Novel, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='recently', to='novels.novel', verbose_name='小说外键')),
                ('chapter', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='recently_chapter', to='novels.novel_chapter', verbose_name='章节id')),
            ],
            options={
                'verbose_name_plural': '最近阅读表',
            },
        ),
        migrations.CreateModel(
            name='Novel_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('Novel', models.ForeignKey(db_constraint=apps.novels.models.Novel, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Novel_list', to='novels.novel', verbose_name='小说外键')),
                ('chapter', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='chapter', to='novels.novel_chapter', verbose_name='章节id')),
            ],
            options={
                'verbose_name_plural': '小说书架表',
            },
        ),
        migrations.AddField(
            model_name='novel',
            name='category',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='novel_category', to='novels.novel_category', verbose_name='小说分类'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_time', models.DateTimeField(auto_now_add=True)),
                ('comment_content', models.TextField()),
                ('up_number', models.IntegerField(default=0)),
                ('Novel', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='novels.novel')),
                ('parent', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='novels.comment')),
            ],
            options={
                'verbose_name_plural': '小说评论表',
            },
        ),
    ]
