# Generated by Django 3.2 on 2024-05-25 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='novel',
            name='dashang',
        ),
        migrations.RemoveField(
            model_name='novel',
            name='is_vip',
        ),
        migrations.RemoveField(
            model_name='novel',
            name='jinpiao',
        ),
        migrations.RemoveField(
            model_name='novel',
            name='shubi',
        ),
    ]
