# Generated by Django 3.2 on 2024-05-25 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('novels', '0002_auto_20240525_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='author_user',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='author', to='users.user', verbose_name='是否是本网站用户'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(db_constraint=False, default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='users.user'),
        ),
        migrations.AddField(
            model_name='novel_list',
            name='user',
            field=models.ForeignKey(db_constraint=False, default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user', to='users.user', verbose_name='用户外键'),
        ),
        migrations.AddField(
            model_name='recently_reading',
            name='user',
            field=models.ForeignKey(db_constraint=False, default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='recently_user', to='users.user', verbose_name='用户外键'),
        ),
    ]
