# Generated by Django 3.2 on 2024-06-01 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0003_auto_20240525_2038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='parent',
        ),
        migrations.AlterField(
            model_name='novel_chapter',
            name='content',
            field=models.FileField(upload_to='chapter_contents/', verbose_name='章节内容'),
        ),
    ]
