# Generated by Django 3.2 on 2024-06-01 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0004_auto_20240601_1906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='novel_chapter',
            name='id',
        ),
        migrations.AddField(
            model_name='novel_chapter',
            name='chapter_id',
            field=models.IntegerField(default=-1, primary_key=True, serialize=False),
        ),
    ]
