# Generated by Django 3.2 on 2024-06-02 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0005_auto_20240601_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='Novel',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='novel_comments', to='novels.novel'),
        ),
        migrations.AlterField(
            model_name='novel_chapter',
            name='content',
            field=models.FileField(blank=True, upload_to='novel_content', verbose_name='章节内容'),
        ),
    ]
