# Generated by Django 3.2 on 2024-06-02 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0006_auto_20240602_2108'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='Novel',
            new_name='novel',
        ),
        migrations.AddField(
            model_name='comment',
            name='chapter',
            field=models.ForeignKey(db_constraint=False, default=0, on_delete=django.db.models.deletion.CASCADE, related_name='chapter_comments', to='novels.novel_chapter'),
        ),
    ]
