# Generated by Django 3.2 on 2024-06-03 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0009_auto_20240603_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novel_chapter',
            name='chapter_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='novel_chapter',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
