# Generated by Django 3.2 on 2024-06-03 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_author'),
        ('novels', '0010_auto_20240603_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='author_user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='author', to='users.user'),
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cfi', models.CharField(max_length=255, verbose_name='CFI位置')),
                ('note', models.TextField(verbose_name='笔记内容')),
                ('is_public', models.BooleanField(default=False, verbose_name='是否公开')),
                ('novel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novels.novel', verbose_name='小说')),
                ('novel_chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novels.novel_chapter', verbose_name='章节')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user', verbose_name='用户')),
            ],
        ),
    ]
