# Generated by Django 3.2 on 2024-06-07 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0011_auto_20240603_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='type',
            field=models.CharField(default=None, max_length=255, verbose_name='具体类型'),
        ),
        migrations.AlterField(
            model_name='novel_chapter',
            name='chapter_id',
            field=models.IntegerField(default=0),
        ),
    ]
