# Generated by Django 3.2 on 2024-06-03 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0011_auto_20240603_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novel_chapter',
            name='chapter_id',
            field=models.IntegerField(default=0),
        ),
    ]
