# Generated by Django 3.2 on 2024-06-07 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0012_auto_20240607_1927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='novel_chapter',
            name='is_free',
        ),
        migrations.RemoveField(
            model_name='novel_chapter',
            name='price',
        ),
    ]
