# Generated by Django 3.2 on 2024-06-07 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0013_auto_20240607_2118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='novel_chapter',
            name='novel_chapter',
        ),
        migrations.AddField(
            model_name='novel_chapter',
            name='title',
            field=models.CharField(default=None, max_length=64, verbose_name='章节标题'),
        ),
        migrations.AlterField(
            model_name='novel_chapter',
            name='chapter_id',
            field=models.IntegerField(default=0, verbose_name='章节号'),
        ),
    ]
