# Generated by Django 3.2 on 2024-06-08 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0012_alter_novel_chapter_chapter_id'),
        ('novels', '0014_auto_20240607_2128'),
    ]

    operations = [
    ]
