# Generated by Django 3.2 on 2024-06-08 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0013_merge_20240607_2011'),
        ('novels', '0014_auto_20240607_2128'),
    ]

    operations = [
    ]
