# Generated by Django 3.2 on 2024-06-08 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0015_merge_20240608_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novel_chapter',
            name='chapter_id',
            field=models.IntegerField(default=0, verbose_name='章节号'),
        ),
    ]
