# Generated by Django 3.2 on 2024-06-09 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0015_merge_20240609_1555'),
        ('novels', '0016_alter_novel_chapter_chapter_id'),
    ]

    operations = [
    ]
