# Generated by Django 3.2 on 2024-06-09 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0016_alter_novel_chapter_chapter_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='novel_list',
            name='chapter',
        ),
    ]
