# Generated by Django 3.2 on 2024-06-09 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0017_merge_20240609_0756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='novel_list',
            name='chapter',
        ),
    ]
