# Generated by Django 4.2.15 on 2024-08-23 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("author_name", models.CharField(max_length=32, verbose_name="作者")),
                (
                    "author_gender",
                    models.IntegerField(
                        choices=[(0, "男"), (1, "女")], default=0, verbose_name="作者性别"
                    ),
                ),
                ("author_detail", models.TextField(default="", verbose_name="作者简介")),
                (
                    "author_icon",
                    models.FileField(
                        default="icon/default.jpg",
                        upload_to="icon/",
                        verbose_name="作者图片",
                    ),
                ),
                ("user_id", models.IntegerField(null=True, verbose_name="用户ID")),
            ],
            options={
                "verbose_name_plural": "作者表",
            },
        ),
    ]
