# Generated by Django 4.2.15 on 2024-08-23 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("novel", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Novel_category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category_name", models.CharField(max_length=64, verbose_name="分类名字")),
                (
                    "category_file",
                    models.FileField(
                        default="category/default.jpg",
                        upload_to="category/",
                        verbose_name="分类图片",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "小说分类表",
            },
        ),
        migrations.CreateModel(
            name="Novel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "novel_img",
                    models.FileField(
                        default="image/default.jpg",
                        upload_to="image/",
                        verbose_name="小说图片",
                    ),
                ),
                (
                    "novel_status",
                    models.IntegerField(
                        choices=[(0, "连载中"), (1, "已完结")], verbose_name="小说状态"
                    ),
                ),
                ("novel_name", models.CharField(max_length=64, verbose_name="小说名字")),
                ("detail", models.TextField(verbose_name="小说简介")),
                ("tuijian", models.IntegerField(default=0, verbose_name="推荐数量")),
                ("dianji", models.IntegerField(default=0, verbose_name="点击数量")),
                ("total_words", models.IntegerField(default=0, verbose_name="总字数")),
                (
                    "chapter_start",
                    models.IntegerField(default=0, verbose_name="小说章节开始id"),
                ),
                (
                    "chapter_end",
                    models.IntegerField(default=0, verbose_name="小说章节结束id"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="Novel",
                        to="novel.author",
                        verbose_name="小说作者",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="novel_category",
                        to="novel.novel_category",
                        verbose_name="小说分类",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "小说表",
            },
        ),
    ]
