# Generated by Django 4.2.15 on 2024-08-23 16:19

from django.db import migrations, models
import django.db.models.deletion
import novel.models


class Migration(migrations.Migration):

    dependencies = [
        ("novel", "0002_novel_category_novel"),
    ]

    operations = [
        migrations.CreateModel(
            name="Novel_list",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.IntegerField(null=True, verbose_name="用户ID")),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "Novel",
                    models.ForeignKey(
                        db_constraint=novel.models.Novel,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="Novel_list",
                        to="novel.novel",
                        verbose_name="小说外键",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "小说书架表",
            },
        ),
    ]
